{{/* Copyright 2026 © Amazon.com and Affiliates: This deliverable is considered Developed Content as defined in the AWS Service Terms. */}}

{{- if and .Values.adminUi.enabled .Values.adminUi.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "llm-gateway.fullname" . }}-admin-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-gateway.componentLabels" (dict "root" . "component" "admin-ui") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "llm-gateway.fullname" . }}-admin-ui
  minReplicas: {{ .Values.adminUi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.adminUi.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.adminUi.autoscaling.targetCPUUtilizationPercentage }}
    {{- if .Values.adminUi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.adminUi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
