{{/* Copyright 2026 © Amazon.com and Affiliates: This deliverable is considered Developed Content as defined in the AWS Service Terms. */}}

{{- if and .Values.gatewayProxy.enabled .Values.gatewayProxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-gateway.serviceAccountName" (dict "root" . "svc" .Values.gatewayProxy "default" "gateway-proxy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-gateway.componentLabels" (dict "root" . "component" "gateway-proxy") | nindent 4 }}
  {{- with .Values.gatewayProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
