/**
 * 뷰 하나당 단일 HTML 파일을 만든다:
 *   index.html + src/main.ts → ../app.html  (platform-telemetry 뷰)
 *
 * vite-plugin-singlefile이 SDK와 스타일을 HTML 하나에 인라인한다. 서버(`server.py`)는
 * 이 파일들을 읽어 `resources/read`로 내보내므로 런타임에 Node가 필요 없고, 결과물을
 * 커밋해 두면 파이썬만으로도 배포(`agentcore launch`)가 된다.
 *
 * 뷰마다 `build()`를 따로 돈다: 한 번의 빌드에 입력을 여럿 주면 vite가 공용 청크를
 * 뽑아내는데, singlefile 플러그인은 그것을 각 HTML에 인라인하지 않는다.
 */
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, "dist");

const VIEWS = [{ input: "index.html", output: "app.html" }];

rmSync(dist, { recursive: true, force: true });

for (const view of VIEWS) {
  const outDir = resolve(dist, view.output.replace(/\.html$/, ""));
  await build({
    root: here,
    plugins: [viteSingleFile()],
    logLevel: "warn",
    build: {
      outDir,
      emptyOutDir: true,
      // 규격 CSP 기본값은 script-src 'self' 'unsafe-inline'이다 — 인라인 스크립트는
      // 허용되지만 외부 청크는 아니므로 반드시 단일 파일이어야 한다.
      modulePreload: false,
      cssCodeSplit: false,
      assetsInlineLimit: Number.MAX_SAFE_INTEGER,
      rollupOptions: { input: resolve(here, view.input) },
    },
  });

  const built = readFileSync(resolve(outDir, view.input), "utf-8");
  const banner = `<!-- GENERATED by mcp-apps-server/app (npm run build). Edit app/${view.input} and its src/ module instead. -->\n`;
  const target = resolve(here, "..", view.output);
  writeFileSync(target, banner + built);
  console.log(`built ${target} (${(Buffer.byteLength(built) / 1024).toFixed(1)} KB)`);
}
